notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

version: 1.0.{build}

branches:
  only:
    - master

os: Visual Studio 2013

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.6\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86'
  - qmake qwebengine.pro
  - dir
  - nmake
  - dir

after_build:
  - cd release
  - windeployqt --no-compiler-runtime --no-translations --release qwebengine.exe
  - ps : rm *.cpp
  - ps : rm *.h
  - ps : rm *.obj
  - dir

artifacts:
  - path: release
    name: qwebengine
  - path: release/qwebengine.exe
    name: qwebengine.exe
